declare module 'remark-html';
declare module 'remark';
declare module 'remark-parse';
declare module 'remark-gfm';
declare module 'remark-rehype';
declare module 'rehype-stringify';
declare module 'rehype-highlight';
declare module 'remark-slug';
declare module 'remark-toc'; 